---
new_page_extension: md
auto_deploy: false
admin_path: src/admin
webhook_url: 
sections:
- type: directory
  path: src/posts
  label: Posts
  create: all
  match: "**/*.md"
  templates:
  - blog-post
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*.md"
  templates:
  - data
- type: directory
  path: src/_data
  label: Data
  create: all
  match: "**/*.json"
  new_doc_ext: json
upload_dir: src/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: docs
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npx eleventy --serve
