name: Eleventy Build
on:
  workflow_dispatch:
  #push:
    #paths-ignore: #don't build live site if only committed to drafts folder, changed forestry config or changed github config
    #  - 'src/posts/drafts/**' 
    #  - '.forestry/**' 
    #  - '.github/**' 
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '1 3 * * *'

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
        with:
          install_dependencies: true 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs 
          publish_branch: gh-pages
